
pool:
  name: local

jobs:
- job: CI
  displayName: "CI for $(Build.Repository.Name)"
  steps:
  - task: NodeTool@0
    displayName: "Install node 16"
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'
  - script: |
      npm install
      npm run test
      npm run coverage
    displayName: "Run install, test and coverage"
  - task: PublishTestResults@2
    displayName: "Publish and check test results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit.xml'
      failTaskOnFailedTests: true
