
pool:
  name: local

steps:
- script: echo $(Build.BuildUri) $(Build.BuildId)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'build $(Build.Repository.Name)'
