pool:
  name: local

jobs:
- job: CI
  displayName: "CI for $(Build.Repository.Name)"
  steps:
  - task: NodeTool@0
    displayName: "Install node 16"
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonarqubek8s'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'nodejsapp-julian'
      cliProjectName: 'nodejsapp-julian'
      cliProjectVersion: '$(Build.SourceVersion)'
      cliSources: '.'
      extraProperties: |
        sonar.sources=./src
        sonar.tests=./test
        sonar.sourceEncoding=UTF-8
        sonar.javascript.lcov.reportPaths=./coverage/lcov.info
        sonar.testExecutionReportPaths=./coverage/sonar-report.xml
  - script: |
      npm install
      npm run test
      npm run coverage
    displayName: "Run install, test and coverage"
  - task: PublishTestResults@2
    displayName: "Publish and check test results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit.xml'
      failTaskOnFailedTests: true
  - task: SonarQubeAnalyze@5
    inputs:
      jdkversion: 'JAVA_HOME'
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'