pool:
  name: local

trigger:
  - develop
  - release
  - master

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    - name: environment
      value: dev
  - ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    - name: environment
      value: test
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - name: environment
      value: prod

stages:
  - stage: docker
    displayName: "docker build and push ${{ variables.environment }}"
    jobs:
      - job: docker
        steps:
          - task: Docker@2
            displayName: "docker build and push"
            inputs:
              containerRegistry: 'dockerregistry'
              repository: 'tevolvers/dummy'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              buildContext: '.'
  - stage: k8s
    dependsOn: docker
    displayName: "k8s deploy on ${{ variables.environment }}"
    jobs:
      - deployment:
        displayName: "operadores ${{ variables.environment }}"
        environment:
          name: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: "deploy to k8s cluster"
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'k8s'
                    namespace: 'bingo'
                    command: 'apply'
                    useConfigurationFile: true
                    configurationType: 'inline'
                    inline: |
                      apiVersion: apps/v1
                      kind: Deployment
                      metadata:
                        labels:
                          app: dummy
                          project: bingo
                        name: dummy
                        namespace: bingo
                      spec:
                        replicas: 1
                        selector:
                          matchLabels:
                            app: dummy
                        template:
                          metadata:
                            labels:
                              app: dummy
                          spec:
                            containers:
                            - name: dummy
                              image: tevolvers/dummy:$(Build.BuildId)
                              imagePullPolicy: "Always"
                              env:
                              - name: MESSAGE
                                value: $(environment)
                              - name: ID
                                value: $(Build.BuildId)
                              ports:
                              - containerPort: 3000
                            imagePullSecrets:
                            - name: secretregistry
                        strategy:
                          type: RollingUpdate
                          rollingUpdate:
                            maxUnavailable: 1
                            maxSurge: 0
                      ---
                      apiVersion: v1
                      kind: Service
                      metadata:
                        name: dummy
                        namespace: bingo
                        labels:
                          app: dummy
                          project: bingo
                      spec:
                        type: LoadBalancer
                        ports:
                        - name: http
                          port: 80
                          targetPort: 3000
                        selector:
                          app: dummy

  

